CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    firstname VARCHAR NOT NULL,
    lastname VARCHAR NOT NULL,
    email VARCHAR NOT NULL UNIQUE,
    phone VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    status BOOLEAN NULL DEFAULT true,
    createdat TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users_personal_data (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    sex VARCHAR NOT NULL,
    address VARCHAR NOT NULL,
    date_of_birth VARCHAR NOT NULL,
    country VARCHAR NOT NULL,
    city VARCHAR NOT NULL,
    createdat TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE users_registration (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    type SMALLINT NOT NULL,
    code VARCHAR NOT NULL,
    status BOOLEAN NULL,
    createdat TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE users_measurements (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    date VARCHAR NOT NULL,
    hour VARCHAR NOT NULL,
    value INTEGER NOT NULL,
    createdat TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE users_auth (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    access_token VARCHAR NOT NULL,
    refresh_token VARCHAR NOT NULL,
    createdat TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id)
);
